name: deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout config
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up React build
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install React project dependencies
        run: npm install

      - name: Build static React site
        run: npm run build

      - name: Setup deployment
        run: |
          mkdir -p ./publish
          mv -f build/* ./publish/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          force_orphan: true
